package cat.proven.utils.database;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;

/**
 * generic DAO
 * loads queries and uses reflection
 * @author Jose
 * @param <T> the base type of DAO
 */
public abstract class DbDao<T> {

    /**
     * queries for this object
     */
    protected Properties queries;
    /**
     * the path to the file with the queries
     */
    protected String queriesFile;
    /**
     * DbConnector object with connection to database properties
     */
    protected final DbConnectorInterface dbConnector;
    /**
     * connection to use in queries
     */
    protected Connection connection;
    /**
     * keys generated by database after last insert query
     */
    protected List<Object> lastGeneratedKeys;
    
    public DbDao(DbConnectorInterface dbConnector) {
        this.dbConnector = dbConnector;
        this.queries = new Properties();
        initQueries();
        this.lastGeneratedKeys = null;
    }

    /**
     * gets a new connection or existent connection
     * @return connection
     * @throws SQLException 
     */
    public Connection getConnection() throws SQLException {
        if ((connection == null) || (!connection.isValid(0))) {
            connection = this.dbConnector.getConnection();
        }
        return connection;
    }

    /**
     * sets connection created out of this method (for transactions)
     * @param connection the connection to set
     */
    public void setConnection(Connection connection) {
        this.connection = connection;
    }

    /**
     * gets last generated keys saved with last insert query
     * @return list of keys
     */
    public List<Object> getLastGeneratedKeys() {
        return lastGeneratedKeys;
    }
    
    /**
     * converts resultset row to T object
     *
     * @param rs the resultset obtained in last query
     * @return T object with data of current row
     * @throws SQLException
     */
    protected abstract T fromResultSet(ResultSet rs) throws SQLException;

    /**
     * loads queries
     */
    protected abstract void initQueries();
    /**
     * performs select query
     *
     * @param queryName the name of the query (in queries properties)
     * @param values a list of values to be bound to query parameters
     * @return list of T objectes retrieved by query
     * @throws java.sql.SQLException
     */
    public List<T> execQuery(String queryName, List<Object> values) throws SQLException {
        List<T> result = new ArrayList<>();
        Connection conn = getConnection();
        if (conn != null) {
            String query = queries.getProperty(queryName);
            PreparedStatement st = conn.prepareStatement(query);
            for (int i = 0; i < values.size(); i++) {
                st.setObject(i + 1, values.get(i));
            }
            ResultSet rs = st.executeQuery();
            while (rs.next()) {
                T obj = fromResultSet(rs);
                if (obj != null) {
                    result.add(obj);
                }
            }
        }
        return result;
    }

    /**
     * performs update query
     *
     * @param queryName the name of the query (in queries properties)
     * @param values a list of values to be bound to query parameters
     * @return the number of rows affected by query
     * @throws java.sql.SQLException
     */
    public int execUpdate(String queryName, List<Object> values) throws SQLException {
        int result = 0;
        Connection conn = getConnection();
        if (conn != null) {
            String query = queries.getProperty(queryName);
            PreparedStatement st = conn.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);
            for (int i = 0; i < values.size(); i++) {
                st.setObject(i + 1, values.get(i));
            }
            result = st.executeUpdate();
            if (result == 1) {
                ResultSet rs = st.getGeneratedKeys();
                lastGeneratedKeys = new ArrayList<>();
                while (rs.next()) {
                    lastGeneratedKeys.add(rs.getLong(1));
                }
            }
        }
        return result;
    }   
    
    /**
     * performs select where query
     * @param queryName the name of the query
     * @param field the field name
     * @param value the value to select
     * @return list of T objectes retrieved by query
     * @throws SQLException 
     */
    public List<T> execWhereQuery(String queryName, String field, Object value) throws SQLException {
        List<T> result = new ArrayList<>();
        Connection conn = getConnection();
        if (conn != null) {
            String query = queries.getProperty(queryName);
            query = String.format(query, field);
            PreparedStatement st = conn.prepareStatement(query);
            st.setObject(1, value);
            ResultSet rs = st.executeQuery();
            while (rs.next()) {
                T obj = fromResultSet(rs);
                if (obj != null) {
                    result.add(obj);
                }
            }
        }
        return result;
    }
    
}
